# https://taskfile.dev

version: "3"

env:
  ENV: production

dotenv: ["config/{{.ENV}}/secrets.env"]

tasks:

  deps:sync:
    desc: Sync dependencies using uv
    cmds:
      - uv sync

  deps:update:
    desc: Update all dependencies and regenerate requirements.txt
    cmds:
      - uv sync --upgrade
      - task: deps:export

  deps:export:
    deps: [deps:sync]
    desc: Generate requirements.txt from pyproject.toml for GCP Functions
    cmds:
      - uv export --format requirements-txt --no-dev --no-hashes --output-file src/requirements.txt
      - sed -i '/-e \./d' src/requirements.txt

  gcp:check:
    desc: Verify the active GCP project matches the deploy target
    cmds:
      - |
        CURRENT=$(gcloud config get-value project 2>/dev/null)
        if [ "$CURRENT" != "{{.GCP_PROJECT_NAME}}" ]; then
          echo "ERROR: Active GCP project is '$CURRENT', but deploy target is '{{.GCP_PROJECT_NAME}}'." >&2
          echo "Run: gcloud config set project {{.GCP_PROJECT_NAME}}" >&2
          exit 1
        fi
        echo "GCP project OK: $CURRENT"
    silent: true

  deploy:gcp:
    deps: [deps:export]
    desc: Deploy using gcloud CLI
    preconditions:
      - sh: '[ "$(gcloud config get-value project 2>/dev/null)" = "{{.GCP_PROJECT_NAME}}" ]'
        msg: "Wrong GCP project. Run: gcloud config set project {{.GCP_PROJECT_NAME}}"
    cmds:
      - sh deploy.sh

  deploy:plan:
    desc: Run terraform plan without applying
    preconditions:
      - sh: '[ "$(gcloud config get-value project 2>/dev/null)" = "{{.GCP_PROJECT_NAME}}" ]'
        msg: "Wrong GCP project. Run: gcloud config set project {{.GCP_PROJECT_NAME}}"
    cmds:
      - |
        eval $(yq -r 'to_entries[] | "export \(.key)=\(.value)"' config/production/config.yaml)
        cd terraform
        terraform init
        terraform plan

  deploy:terraform:
    deps: [deps:export]
    desc: Deploy using terraform (init + plan + apply)
    preconditions:
      - sh: '[ "$(gcloud config get-value project 2>/dev/null)" = "{{.GCP_PROJECT_NAME}}" ]'
        msg: "Wrong GCP project. Run: gcloud config set project {{.GCP_PROJECT_NAME}}"
    cmds:
      - sh deploy_terraform.sh

  test:
    deps: [deps:sync]
    desc: Run unit tests
    cmds:
      - uv run pytest tests/ -v

  test:watch:
    deps: [deps:sync]
    desc: Run tests in watch mode
    cmds:
      - uv run pytest-watch tests/ -v

  structurizr:
    desc: Run Structurizr Lite server for C4 diagrams
    dir: docs/c4
    cmds:
      - docker compose down
      - docker compose up -d
